INSERT INTO bicycle_station(name)VALUES ('Station1');
INSERT INTO bicycle_station(name)VALUES ('Station2');
INSERT INTO bicycle(model_name,station_id,bicycle_status)VALUES ('model1', 1, 'FREE');
INSERT INTO bicycle(model_name,station_id,bicycle_status)VALUES ('model2', 1, 'FREE');
INSERT INTO bicycle(model_name,station_id,bicycle_status)VALUES ('model3', 2, 'FREE');
INSERT INTO bicycle(model_name,station_id,bicycle_status)VALUES ('model4', 2, 'FREE');
INSERT INTO bicycle(model_name,station_id,bicycle_status)VALUES ('model5', 2, 'OCCUPIED');
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model6', 1);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model7', 1);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model8', 1);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('modeINSERT INTOl9', 1);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model10', 1);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model11', 1);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model12', 2);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model13', 2);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model14', 2);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model15', 2);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model15', 2);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model16', 2);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model17', 2);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model18', 2);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model19', 2);
-- INSERT INTO bicycle(model_name,station_id)VALUES ('model20', 2);
INSERT INTO bicycle_stand(name, stand_status,station_id)VALUES ('Stand1', 'FREE',1);
INSERT INTO bicycle_stand(name, stand_status,station_id)VALUES ('Stand2', 'FREE', 2);
INSERT INTO bicycle_stand(name, stand_status,station_id)VALUES ('Stand3', 'FREE', 2);
INSERT INTO bicycle_stand(name, stand_status,station_id)VALUES ('Stand4', 'OCCUPIED', 1);
INSERT INTO bicycle_stand(name, stand_status,station_id)VALUES ('Stand5', 'OCCUPIED', 2);
